package erpsolwom.erpsolwommodel.erpsolwomvo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat May 11 15:36:22 PKT 2024
// ---------------------------------------------------------------------
public interface SrPoReceivingHeaderVO extends ViewObject {
    void doSuperviseSrPOReceiving();
}

