package erpsolwom.erpsolwommodel.erpsolwomvo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed May 08 23:23:18 PKT 2024
// ---------------------------------------------------------------------
public interface SrPurchaseBidCompareHeaderView extends ViewObject {
    void doSuperviseSrPurchaseComp();
}

