package erpsolwom.erpsolwommodel.erpsolwomvo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed May 08 16:17:10 PKT 2024
// ---------------------------------------------------------------------
public interface SrPurchaseBidHeaderView extends ViewObject {
    void doSuperviseSrPurchaseBID();
}

