package erpsolwom.erpsolwommodel.erpsolwomvo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun May 05 11:09:11 PKT 2024
// ---------------------------------------------------------------------
public interface SrPurchaseRfqHeaderView extends ViewObject {
    void doSuperviseSrPurchaseRFQ();
}

