package erpsolwom.erpsolwommodel.erpsolwomvo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat May 04 11:01:47 PKT 2024
// ---------------------------------------------------------------------
public interface SrPurchaseDemandHeaderView extends ViewObject {
    void doSuperviseSrPurchaseDemand();
}

