package erpsolwom.erpsolwommodel.erpsolwomvo.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun May 12 11:35:03 PKT 2024
// ---------------------------------------------------------------------
public interface VwBidCompareForPoGenerateVORow extends Row {
    void doGeneratePOFromBidCompare();
}

