package erpsolwom.erpsolwommodel.erpsolwomeo;

import erpsolglob.erpsolglobmodel.erpsolglobclasses.ERPSolGlobalsEntityImpl;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon May 27 23:10:11 PKT 2024
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SrPoInvoicePayAdvanceImpl extends ERPSolGlobalsEntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Payadvanceseq,
        Invoicepayseq,
        AdvanceCode,
        AdvanceAmount,
        Remarks,
        CreatedBy,
        CreatedDate,
        ModifiedBy,
        ModifiedDate,
        Posted,
        PostedDate,
        SrPoInvoicePayHeader;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int PAYADVANCESEQ = AttributesEnum.Payadvanceseq.index();
    public static final int INVOICEPAYSEQ = AttributesEnum.Invoicepayseq.index();
    public static final int ADVANCECODE = AttributesEnum.AdvanceCode.index();
    public static final int ADVANCEAMOUNT = AttributesEnum.AdvanceAmount.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int MODIFIEDBY = AttributesEnum.ModifiedBy.index();
    public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
    public static final int POSTED = AttributesEnum.Posted.index();
    public static final int POSTEDDATE = AttributesEnum.PostedDate.index();
    public static final int SRPOINVOICEPAYHEADER = AttributesEnum.SrPoInvoicePayHeader.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SrPoInvoicePayAdvanceImpl() {
    }

    /**
     * Gets the attribute value for Payadvanceseq, using the alias name Payadvanceseq.
     * @return the value of Payadvanceseq
     */
    public BigDecimal getPayadvanceseq() {
        return (BigDecimal) getAttributeInternal(PAYADVANCESEQ);
    }

    /**
     * Sets <code>value</code> as the attribute value for Payadvanceseq.
     * @param value value to set the Payadvanceseq
     */
    public void setPayadvanceseq(BigDecimal value) {
        setAttributeInternal(PAYADVANCESEQ, value);
    }

    /**
     * Gets the attribute value for Invoicepayseq, using the alias name Invoicepayseq.
     * @return the value of Invoicepayseq
     */
    public BigDecimal getInvoicepayseq() {
        return (BigDecimal) getAttributeInternal(INVOICEPAYSEQ);
    }

    /**
     * Sets <code>value</code> as the attribute value for Invoicepayseq.
     * @param value value to set the Invoicepayseq
     */
    public void setInvoicepayseq(BigDecimal value) {
        setAttributeInternal(INVOICEPAYSEQ, value);
    }

    /**
     * Gets the attribute value for AdvanceCode, using the alias name AdvanceCode.
     * @return the value of AdvanceCode
     */
    public String getAdvanceCode() {
        return (String) getAttributeInternal(ADVANCECODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for AdvanceCode.
     * @param value value to set the AdvanceCode
     */
    public void setAdvanceCode(String value) {
        setAttributeInternal(ADVANCECODE, value);
    }

    /**
     * Gets the attribute value for AdvanceAmount, using the alias name AdvanceAmount.
     * @return the value of AdvanceAmount
     */
    public BigDecimal getAdvanceAmount() {
        return (BigDecimal) getAttributeInternal(ADVANCEAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for AdvanceAmount.
     * @param value value to set the AdvanceAmount
     */
    public void setAdvanceAmount(BigDecimal value) {
        setAttributeInternal(ADVANCEAMOUNT, value);
    }

    /**
     * Gets the attribute value for Remarks, using the alias name Remarks.
     * @return the value of Remarks
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Remarks.
     * @param value value to set the Remarks
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Timestamp value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for ModifiedBy, using the alias name ModifiedBy.
     * @return the value of ModifiedBy
     */
    public String getModifiedBy() {
        return (String) getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for ModifiedBy.
     * @param value value to set the ModifiedBy
     */
    public void setModifiedBy(String value) {
        setAttributeInternal(MODIFIEDBY, value);
    }

    /**
     * Gets the attribute value for ModifiedDate, using the alias name ModifiedDate.
     * @return the value of ModifiedDate
     */
    public Timestamp getModifiedDate() {
        return (Timestamp) getAttributeInternal(MODIFIEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ModifiedDate.
     * @param value value to set the ModifiedDate
     */
    public void setModifiedDate(Timestamp value) {
        setAttributeInternal(MODIFIEDDATE, value);
    }

    /**
     * Gets the attribute value for Posted, using the alias name Posted.
     * @return the value of Posted
     */
    public String getPosted() {
        return (String) getAttributeInternal(POSTED);
    }

    /**
     * Sets <code>value</code> as the attribute value for Posted.
     * @param value value to set the Posted
     */
    public void setPosted(String value) {
        setAttributeInternal(POSTED, value);
    }

    /**
     * Gets the attribute value for PostedDate, using the alias name PostedDate.
     * @return the value of PostedDate
     */
    public Timestamp getPostedDate() {
        return (Timestamp) getAttributeInternal(POSTEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for PostedDate.
     * @param value value to set the PostedDate
     */
    public void setPostedDate(Timestamp value) {
        setAttributeInternal(POSTEDDATE, value);
    }

    /**
     * @return the associated entity SrPoInvoicePayHeaderImpl.
     */
    public SrPoInvoicePayHeaderImpl getSrPoInvoicePayHeader() {
        return (SrPoInvoicePayHeaderImpl) getAttributeInternal(SRPOINVOICEPAYHEADER);
    }

    /**
     * Sets <code>value</code> as the associated entity SrPoInvoicePayHeaderImpl.
     */
    public void setSrPoInvoicePayHeader(SrPoInvoicePayHeaderImpl value) {
        setAttributeInternal(SRPOINVOICEPAYHEADER, value);
    }

    /**
     * @param payadvanceseq key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal payadvanceseq) {
        return new Key(new Object[] { payadvanceseq });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("erpsolwom.erpsolwommodel.erpsolwomeo.SrPoInvoicePayAdvance");
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
    }
}

