package erpsolwom.erpsolwommodel.erpsolwomeo;

import erpsolglob.erpsolglobmodel.erpsolglobclasses.ERPSolGlobalsEntityImpl;

import java.math.BigDecimal;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed May 08 15:09:21 PKT 2024
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SrPurchaseBidLinesImpl extends ERPSolGlobalsEntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Bidlinesseq,
        Bidheaderseq,
        Rfqlinesseqno,
        Demandlinesseq,
        Quantity,
        BidPrice,
        TaxPercent,
        NetPrice,
        Remarks,
        ProjectId,
        DepartmentId,
        SupplierItemName,
        CreatedBy,
        CreatedDate,
        ModifiedBy,
        Modifieddate,
        ItemId,
        txtItemName,
        txtTaxAmount,
        txtNetAmount,
        txtSupplierId,
        SrPurchaseBidHeader,
        SrItems;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int BIDLINESSEQ = AttributesEnum.Bidlinesseq.index();
    public static final int BIDHEADERSEQ = AttributesEnum.Bidheaderseq.index();
    public static final int RFQLINESSEQNO = AttributesEnum.Rfqlinesseqno.index();
    public static final int DEMANDLINESSEQ = AttributesEnum.Demandlinesseq.index();
    public static final int QUANTITY = AttributesEnum.Quantity.index();
    public static final int BIDPRICE = AttributesEnum.BidPrice.index();
    public static final int TAXPERCENT = AttributesEnum.TaxPercent.index();
    public static final int NETPRICE = AttributesEnum.NetPrice.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int PROJECTID = AttributesEnum.ProjectId.index();
    public static final int DEPARTMENTID = AttributesEnum.DepartmentId.index();
    public static final int SUPPLIERITEMNAME = AttributesEnum.SupplierItemName.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int MODIFIEDBY = AttributesEnum.ModifiedBy.index();
    public static final int MODIFIEDDATE = AttributesEnum.Modifieddate.index();
    public static final int ITEMID = AttributesEnum.ItemId.index();
    public static final int TXTITEMNAME = AttributesEnum.txtItemName.index();
    public static final int TXTTAXAMOUNT = AttributesEnum.txtTaxAmount.index();
    public static final int TXTNETAMOUNT = AttributesEnum.txtNetAmount.index();
    public static final int TXTSUPPLIERID = AttributesEnum.txtSupplierId.index();
    public static final int SRPURCHASEBIDHEADER = AttributesEnum.SrPurchaseBidHeader.index();
    public static final int SRITEMS = AttributesEnum.SrItems.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SrPurchaseBidLinesImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("erpsolwom.erpsolwommodel.erpsolwomeo.SrPurchaseBidLines");
    }


    /**
     * Gets the attribute value for Bidlinesseq, using the alias name Bidlinesseq.
     * @return the value of Bidlinesseq
     */
    public Integer getBidlinesseq() {
        return (Integer) getAttributeInternal(BIDLINESSEQ);
    }

    /**
     * Sets <code>value</code> as the attribute value for Bidlinesseq.
     * @param value value to set the Bidlinesseq
     */
    public void setBidlinesseq(Integer value) {
        setAttributeInternal(BIDLINESSEQ, value);
    }

    /**
     * Gets the attribute value for Bidheaderseq, using the alias name Bidheaderseq.
     * @return the value of Bidheaderseq
     */
    public Integer getBidheaderseq() {
        return (Integer) getAttributeInternal(BIDHEADERSEQ);
    }

    /**
     * Sets <code>value</code> as the attribute value for Bidheaderseq.
     * @param value value to set the Bidheaderseq
     */
    public void setBidheaderseq(Integer value) {
        setAttributeInternal(BIDHEADERSEQ, value);
    }

    /**
     * Gets the attribute value for Rfqlinesseqno, using the alias name Rfqlinesseqno.
     * @return the value of Rfqlinesseqno
     */
    public Integer getRfqlinesseqno() {
        return (Integer) getAttributeInternal(RFQLINESSEQNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for Rfqlinesseqno.
     * @param value value to set the Rfqlinesseqno
     */
    public void setRfqlinesseqno(Integer value) {
        setAttributeInternal(RFQLINESSEQNO, value);
    }

    /**
     * Gets the attribute value for Demandlinesseq, using the alias name Demandlinesseq.
     * @return the value of Demandlinesseq
     */
    public Integer getDemandlinesseq() {
        return (Integer) getAttributeInternal(DEMANDLINESSEQ);
    }

    /**
     * Sets <code>value</code> as the attribute value for Demandlinesseq.
     * @param value value to set the Demandlinesseq
     */
    public void setDemandlinesseq(Integer value) {
        setAttributeInternal(DEMANDLINESSEQ, value);
    }

    /**
     * Gets the attribute value for Quantity, using the alias name Quantity.
     * @return the value of Quantity
     */
    public BigDecimal getQuantity() {
        return (BigDecimal) getAttributeInternal(QUANTITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Quantity.
     * @param value value to set the Quantity
     */
    public void setQuantity(BigDecimal value) {
        setAttributeInternal(QUANTITY, value);
    }

    /**
     * Gets the attribute value for BidPrice, using the alias name BidPrice.
     * @return the value of BidPrice
     */
    public BigDecimal getBidPrice() {
        return (BigDecimal) getAttributeInternal(BIDPRICE);
    }

    /**
     * Sets <code>value</code> as the attribute value for BidPrice.
     * @param value value to set the BidPrice
     */
    public void setBidPrice(BigDecimal value) {
        setAttributeInternal(BIDPRICE, value);
    }

    /**
     * Gets the attribute value for TaxPercent, using the alias name TaxPercent.
     * @return the value of TaxPercent
     */
    public BigDecimal getTaxPercent() {
        return (BigDecimal) getAttributeInternal(TAXPERCENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for TaxPercent.
     * @param value value to set the TaxPercent
     */
    public void setTaxPercent(BigDecimal value) {
        setAttributeInternal(TAXPERCENT, value);
    }

    /**
     * Gets the attribute value for NetPrice, using the alias name NetPrice.
     * @return the value of NetPrice
     */
    public BigDecimal getNetPrice() {
        return (BigDecimal) getAttributeInternal(NETPRICE);
    }

    /**
     * Sets <code>value</code> as the attribute value for NetPrice.
     * @param value value to set the NetPrice
     */
    public void setNetPrice(BigDecimal value) {
        setAttributeInternal(NETPRICE, value);
    }

    /**
     * Gets the attribute value for Remarks, using the alias name Remarks.
     * @return the value of Remarks
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Remarks.
     * @param value value to set the Remarks
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for ProjectId, using the alias name ProjectId.
     * @return the value of ProjectId
     */
    public Integer getProjectId() {
        return (Integer) getAttributeInternal(PROJECTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProjectId.
     * @param value value to set the ProjectId
     */
    public void setProjectId(Integer value) {
        setAttributeInternal(PROJECTID, value);
    }

    /**
     * Gets the attribute value for DepartmentId, using the alias name DepartmentId.
     * @return the value of DepartmentId
     */
    public String getDepartmentId() {
        return (String) getAttributeInternal(DEPARTMENTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DepartmentId.
     * @param value value to set the DepartmentId
     */
    public void setDepartmentId(String value) {
        setAttributeInternal(DEPARTMENTID, value);
    }

    /**
     * Gets the attribute value for SupplierItemName, using the alias name SupplierItemName.
     * @return the value of SupplierItemName
     */
    public String getSupplierItemName() {
        return (String) getAttributeInternal(SUPPLIERITEMNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for SupplierItemName.
     * @param value value to set the SupplierItemName
     */
    public void setSupplierItemName(String value) {
        setAttributeInternal(SUPPLIERITEMNAME, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for ModifiedBy, using the alias name ModifiedBy.
     * @return the value of ModifiedBy
     */
    public String getModifiedBy() {
        return (String) getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for ModifiedBy.
     * @param value value to set the ModifiedBy
     */
    public void setModifiedBy(String value) {
        setAttributeInternal(MODIFIEDBY, value);
    }

    /**
     * Gets the attribute value for Modifieddate, using the alias name Modifieddate.
     * @return the value of Modifieddate
     */
    public Date getModifieddate() {
        return (Date) getAttributeInternal(MODIFIEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Modifieddate.
     * @param value value to set the Modifieddate
     */
    public void setModifieddate(Date value) {
        setAttributeInternal(MODIFIEDDATE, value);
    }


    /**
     * Gets the attribute value for ItemId, using the alias name ItemId.
     * @return the value of ItemId
     */
    public Integer getItemId() {
        return (Integer) getAttributeInternal(ITEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItemId.
     * @param value value to set the ItemId
     */
    public void setItemId(Integer value) {
        setAttributeInternal(ITEMID, value);
    }

    /**
     * Gets the attribute value for txtItemName, using the alias name txtItemName.
     * @return the value of txtItemName
     */
    public String gettxtItemName() {
        return (String) getAttributeInternal(TXTITEMNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtItemName.
     * @param value value to set the txtItemName
     */
    public void settxtItemName(String value) {
        setAttributeInternal(TXTITEMNAME, value);
    }

    /**
     * Gets the attribute value for txtTaxAmount, using the alias name txtTaxAmount.
     * @return the value of txtTaxAmount
     */
    public BigDecimal gettxtTaxAmount() {
        return (BigDecimal) getAttributeInternal(TXTTAXAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtTaxAmount.
     * @param value value to set the txtTaxAmount
     */
    public void settxtTaxAmount(BigDecimal value) {
        setAttributeInternal(TXTTAXAMOUNT, value);
    }

    /**
     * Gets the attribute value for txtNetAmount, using the alias name txtNetAmount.
     * @return the value of txtNetAmount
     */
    public BigDecimal gettxtNetAmount() {
        return (BigDecimal) getAttributeInternal(TXTNETAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtNetAmount.
     * @param value value to set the txtNetAmount
     */
    public void settxtNetAmount(BigDecimal value) {
        setAttributeInternal(TXTNETAMOUNT, value);
    }

    /**
     * Gets the attribute value for txtSupplierId, using the alias name txtSupplierId.
     * @return the value of txtSupplierId
     */
    public String gettxtSupplierId() {
        return (String) getAttributeInternal(TXTSUPPLIERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtSupplierId.
     * @param value value to set the txtSupplierId
     */
    public void settxtSupplierId(String value) {
        setAttributeInternal(TXTSUPPLIERID, value);
    }

    /**
     * @return the associated entity SrPurchaseBidHeaderImpl.
     */
    public SrPurchaseBidHeaderImpl getSrPurchaseBidHeader() {
        return (SrPurchaseBidHeaderImpl) getAttributeInternal(SRPURCHASEBIDHEADER);
    }

    /**
     * Sets <code>value</code> as the associated entity SrPurchaseBidHeaderImpl.
     */
    public void setSrPurchaseBidHeader(SrPurchaseBidHeaderImpl value) {
        setAttributeInternal(SRPURCHASEBIDHEADER, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getSrItems() {
        return (EntityImpl) getAttributeInternal(SRITEMS);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setSrItems(EntityImpl value) {
        setAttributeInternal(SRITEMS, value);
    }


    /**
     * @param bidlinesseq key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer bidlinesseq) {
        return new Key(new Object[] { bidlinesseq });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        // TODO Implement this method
        setERPSolPKColumnName("Bidlinesseq");
        setERPSolPKSeqName("SR_PURCHASE_BID_lines_seq");
    //        setERPISGenertePK("NO");
    //        SequenceImpl seq = new SequenceImpl("SO_SALES_ORDER_SEQ", getDBTransaction());
    //        setSalesorderseq(seq.getSequenceNumber());
        super.create(attributeList);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        if (operation!=DML_DELETE) {
            populateAttributeAsChanged(NETPRICE, gettxtNetAmount());
       }
        super.doDML(operation, e);
    }
}

