package erpsolwom.erpsolwommodel.erpsolwomeo;

import erpsolglob.erpsolglobmodel.erpsolglobclasses.ERPSolGlobClassModel;
import erpsolglob.erpsolglobmodel.erpsolglobclasses.ERPSolGlobalsEntityImpl;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed May 08 23:07:02 PKT 2024
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SrPurchaseBidCompareLinesImpl extends ERPSolGlobalsEntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Bidcomparelinesseq,
        Bidcompareheaderseq,
        Bidlinesseq,
        Demandlinesseq,
        Supplierid,
        ItemId,
        BidRate,
        TaxRate,
        NetAmount,
        BidCriteriaSno,
        CreatedBy,
        CreatedDate,
        ModifiedBy,
        Modifieddate,
        IsSelect,
        SrPurchaseBidCompareHeader,
        SrItems;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int BIDCOMPARELINESSEQ = AttributesEnum.Bidcomparelinesseq.index();
    public static final int BIDCOMPAREHEADERSEQ = AttributesEnum.Bidcompareheaderseq.index();
    public static final int BIDLINESSEQ = AttributesEnum.Bidlinesseq.index();
    public static final int DEMANDLINESSEQ = AttributesEnum.Demandlinesseq.index();
    public static final int SUPPLIERID = AttributesEnum.Supplierid.index();
    public static final int ITEMID = AttributesEnum.ItemId.index();
    public static final int BIDRATE = AttributesEnum.BidRate.index();
    public static final int TAXRATE = AttributesEnum.TaxRate.index();
    public static final int NETAMOUNT = AttributesEnum.NetAmount.index();
    public static final int BIDCRITERIASNO = AttributesEnum.BidCriteriaSno.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int MODIFIEDBY = AttributesEnum.ModifiedBy.index();
    public static final int MODIFIEDDATE = AttributesEnum.Modifieddate.index();
    public static final int ISSELECT = AttributesEnum.IsSelect.index();
    public static final int SRPURCHASEBIDCOMPAREHEADER = AttributesEnum.SrPurchaseBidCompareHeader.index();
    public static final int SRITEMS = AttributesEnum.SrItems.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SrPurchaseBidCompareLinesImpl() {
    }

    /**
     * Gets the attribute value for Bidcomparelinesseq, using the alias name Bidcomparelinesseq.
     * @return the value of Bidcomparelinesseq
     */
    public Integer getBidcomparelinesseq() {
        return (Integer) getAttributeInternal(BIDCOMPARELINESSEQ);
    }

    /**
     * Sets <code>value</code> as the attribute value for Bidcomparelinesseq.
     * @param value value to set the Bidcomparelinesseq
     */
    public void setBidcomparelinesseq(Integer value) {
        setAttributeInternal(BIDCOMPARELINESSEQ, value);
    }

    /**
     * Gets the attribute value for Bidcompareheaderseq, using the alias name Bidcompareheaderseq.
     * @return the value of Bidcompareheaderseq
     */
    public Integer getBidcompareheaderseq() {
        return (Integer) getAttributeInternal(BIDCOMPAREHEADERSEQ);
    }

    /**
     * Sets <code>value</code> as the attribute value for Bidcompareheaderseq.
     * @param value value to set the Bidcompareheaderseq
     */
    public void setBidcompareheaderseq(Integer value) {
        setAttributeInternal(BIDCOMPAREHEADERSEQ, value);
    }

    /**
     * Gets the attribute value for Bidlinesseq, using the alias name Bidlinesseq.
     * @return the value of Bidlinesseq
     */
    public Integer getBidlinesseq() {
        return (Integer) getAttributeInternal(BIDLINESSEQ);
    }

    /**
     * Sets <code>value</code> as the attribute value for Bidlinesseq.
     * @param value value to set the Bidlinesseq
     */
    public void setBidlinesseq(Integer value) {
        setAttributeInternal(BIDLINESSEQ, value);
    }

    /**
     * Gets the attribute value for Demandlinesseq, using the alias name Demandlinesseq.
     * @return the value of Demandlinesseq
     */
    public Integer getDemandlinesseq() {
        return (Integer) getAttributeInternal(DEMANDLINESSEQ);
    }

    /**
     * Sets <code>value</code> as the attribute value for Demandlinesseq.
     * @param value value to set the Demandlinesseq
     */
    public void setDemandlinesseq(Integer value) {
        setAttributeInternal(DEMANDLINESSEQ, value);
    }

    /**
     * Gets the attribute value for Supplierid, using the alias name Supplierid.
     * @return the value of Supplierid
     */
    public String getSupplierid() {
        return (String) getAttributeInternal(SUPPLIERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Supplierid.
     * @param value value to set the Supplierid
     */
    public void setSupplierid(String value) {
        setAttributeInternal(SUPPLIERID, value);
    }

    /**
     * Gets the attribute value for ItemId, using the alias name ItemId.
     * @return the value of ItemId
     */
    public Integer getItemId() {
        return (Integer) getAttributeInternal(ITEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItemId.
     * @param value value to set the ItemId
     */
    public void setItemId(Integer value) {
        setAttributeInternal(ITEMID, value);
    }

    /**
     * Gets the attribute value for BidRate, using the alias name BidRate.
     * @return the value of BidRate
     */
    public BigDecimal getBidRate() {
        return (BigDecimal) getAttributeInternal(BIDRATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for BidRate.
     * @param value value to set the BidRate
     */
    public void setBidRate(BigDecimal value) {
        setAttributeInternal(BIDRATE, value);
    }

    /**
     * Gets the attribute value for TaxRate, using the alias name TaxRate.
     * @return the value of TaxRate
     */
    public BigDecimal getTaxRate() {
        return (BigDecimal) getAttributeInternal(TAXRATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TaxRate.
     * @param value value to set the TaxRate
     */
    public void setTaxRate(BigDecimal value) {
        setAttributeInternal(TAXRATE, value);
    }

    /**
     * Gets the attribute value for NetAmount, using the alias name NetAmount.
     * @return the value of NetAmount
     */
    public BigDecimal getNetAmount() {
        return (BigDecimal) getAttributeInternal(NETAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for NetAmount.
     * @param value value to set the NetAmount
     */
    public void setNetAmount(BigDecimal value) {
        setAttributeInternal(NETAMOUNT, value);
    }

    /**
     * Gets the attribute value for BidCriteriaSno, using the alias name BidCriteriaSno.
     * @return the value of BidCriteriaSno
     */
    public Integer getBidCriteriaSno() {
        return (Integer) getAttributeInternal(BIDCRITERIASNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for BidCriteriaSno.
     * @param value value to set the BidCriteriaSno
     */
    public void setBidCriteriaSno(Integer value) {
        setAttributeInternal(BIDCRITERIASNO, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Timestamp value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for ModifiedBy, using the alias name ModifiedBy.
     * @return the value of ModifiedBy
     */
    public String getModifiedBy() {
        return (String) getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for ModifiedBy.
     * @param value value to set the ModifiedBy
     */
    public void setModifiedBy(String value) {
        setAttributeInternal(MODIFIEDBY, value);
    }

    /**
     * Gets the attribute value for Modifieddate, using the alias name Modifieddate.
     * @return the value of Modifieddate
     */
    public Timestamp getModifieddate() {
        return (Timestamp) getAttributeInternal(MODIFIEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Modifieddate.
     * @param value value to set the Modifieddate
     */
    public void setModifieddate(Timestamp value) {
        setAttributeInternal(MODIFIEDDATE, value);
    }

    /**
     * Gets the attribute value for IsSelect, using the alias name IsSelect.
     * @return the value of IsSelect
     */
    public String getIsSelect() {
        return (String) getAttributeInternal(ISSELECT);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsSelect.
     * @param value value to set the IsSelect
     */
    public void setIsSelect(String value) {
        setAttributeInternal(ISSELECT, value);
    }

    /**
     * @return the associated entity erpsolglob.erpsolglobmodel.erpsolglobclasses.ERPSolGlobalsEntityImpl.
     */
    public ERPSolGlobalsEntityImpl getSrPurchaseBidCompareHeader() {
        return (ERPSolGlobalsEntityImpl) getAttributeInternal(SRPURCHASEBIDCOMPAREHEADER);
    }

    /**
     * Sets <code>value</code> as the associated entity erpsolglob.erpsolglobmodel.erpsolglobclasses.ERPSolGlobalsEntityImpl.
     */
    public void setSrPurchaseBidCompareHeader(ERPSolGlobalsEntityImpl value) {
        setAttributeInternal(SRPURCHASEBIDCOMPAREHEADER, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getSrItems() {
        return (EntityImpl) getAttributeInternal(SRITEMS);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setSrItems(EntityImpl value) {
        setAttributeInternal(SRITEMS, value);
    }

    /**
     * @param bidcomparelinesseq key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer bidcomparelinesseq) {
        return new Key(new Object[] { bidcomparelinesseq });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("erpsolwom.erpsolwommodel.erpsolwomeo.SrPurchaseBidCompareLines");
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
        @Override
        protected void create(AttributeList attributeList) {
            // TODO Implement this method
            setERPSolPKColumnName("Bidcomparelinesseq");
            setERPSolPKSeqName("SR_PURCHASE_BID_COMP_LINES_SEQ");
        //        setERPISGenertePK("NO");
        //        SequenceImpl seq = new SequenceImpl("SO_SALES_ORDER_SEQ", getDBTransaction());
        //        setSalesorderseq(seq.getSequenceNumber());
            super.create(attributeList);
        }        
   
    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
    }
}

