package erpsolwom.erpsolwommodel.erpsolwomeo;

import erpsolglob.erpsolglobmodel.erpsolglobclasses.ERPSolGlobClassModel;
import erpsolglob.erpsolglobmodel.erpsolglobclasses.ERPSolGlobalsEntityImpl;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun May 05 00:52:20 PKT 2024
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SrPurchaseRfqHeaderImpl extends ERPSolGlobalsEntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Rfqheaderseqno,
        RfqHeaderCode,
        DemandCode,
        BillTo,
        ShipTo,
        RfqDate,
        DueDate,
        Remarks,
        Locationid,
        Posted,
        RfqFor,
        FobTermSno,
        NoteToSupplier,
        ValidFromDate,
        ValidToDate,
        CreatedBy,
        CreatedDate,
        ModifiedBy,
        Modifieddate,
        Companyid,
        txtLocationName,
        SrPurchaseRfqLines,
        AllLocations,
        SrPurchaseDemandHeader,
        SrPurchaseRfqSupplier,
        SrPurchaseBidHeader,
        SrPurchaseBidCompareHeader;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int RFQHEADERSEQNO = AttributesEnum.Rfqheaderseqno.index();
    public static final int RFQHEADERCODE = AttributesEnum.RfqHeaderCode.index();
    public static final int DEMANDCODE = AttributesEnum.DemandCode.index();
    public static final int BILLTO = AttributesEnum.BillTo.index();
    public static final int SHIPTO = AttributesEnum.ShipTo.index();
    public static final int RFQDATE = AttributesEnum.RfqDate.index();
    public static final int DUEDATE = AttributesEnum.DueDate.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int LOCATIONID = AttributesEnum.Locationid.index();
    public static final int POSTED = AttributesEnum.Posted.index();
    public static final int RFQFOR = AttributesEnum.RfqFor.index();
    public static final int FOBTERMSNO = AttributesEnum.FobTermSno.index();
    public static final int NOTETOSUPPLIER = AttributesEnum.NoteToSupplier.index();
    public static final int VALIDFROMDATE = AttributesEnum.ValidFromDate.index();
    public static final int VALIDTODATE = AttributesEnum.ValidToDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int MODIFIEDBY = AttributesEnum.ModifiedBy.index();
    public static final int MODIFIEDDATE = AttributesEnum.Modifieddate.index();
    public static final int COMPANYID = AttributesEnum.Companyid.index();
    public static final int TXTLOCATIONNAME = AttributesEnum.txtLocationName.index();
    public static final int SRPURCHASERFQLINES = AttributesEnum.SrPurchaseRfqLines.index();
    public static final int ALLLOCATIONS = AttributesEnum.AllLocations.index();
    public static final int SRPURCHASEDEMANDHEADER = AttributesEnum.SrPurchaseDemandHeader.index();
    public static final int SRPURCHASERFQSUPPLIER = AttributesEnum.SrPurchaseRfqSupplier.index();
    public static final int SRPURCHASEBIDHEADER = AttributesEnum.SrPurchaseBidHeader.index();
    public static final int SRPURCHASEBIDCOMPAREHEADER = AttributesEnum.SrPurchaseBidCompareHeader.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SrPurchaseRfqHeaderImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("erpsolwom.erpsolwommodel.erpsolwomeo.SrPurchaseRfqHeader");
    }


    /**
     * Gets the attribute value for Rfqheaderseqno, using the alias name Rfqheaderseqno.
     * @return the value of Rfqheaderseqno
     */
    public Integer getRfqheaderseqno() {
        return (Integer) getAttributeInternal(RFQHEADERSEQNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for Rfqheaderseqno.
     * @param value value to set the Rfqheaderseqno
     */
    public void setRfqheaderseqno(Integer value) {
        setAttributeInternal(RFQHEADERSEQNO, value);
    }

    /**
     * Gets the attribute value for RfqHeaderCode, using the alias name RfqHeaderCode.
     * @return the value of RfqHeaderCode
     */
    public String getRfqHeaderCode() {
        return (String) getAttributeInternal(RFQHEADERCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for RfqHeaderCode.
     * @param value value to set the RfqHeaderCode
     */
    public void setRfqHeaderCode(String value) {
        setAttributeInternal(RFQHEADERCODE, value);
    }

    /**
     * Gets the attribute value for DemandCode, using the alias name DemandCode.
     * @return the value of DemandCode
     */
    public String getDemandCode() {
        return (String) getAttributeInternal(DEMANDCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for DemandCode.
     * @param value value to set the DemandCode
     */
    public void setDemandCode(String value) {
        setAttributeInternal(DEMANDCODE, value);
    }

    /**
     * Gets the attribute value for BillTo, using the alias name BillTo.
     * @return the value of BillTo
     */
    public String getBillTo() {
        return (String) getAttributeInternal(BILLTO);
    }

    /**
     * Sets <code>value</code> as the attribute value for BillTo.
     * @param value value to set the BillTo
     */
    public void setBillTo(String value) {
        setAttributeInternal(BILLTO, value);
    }

    /**
     * Gets the attribute value for ShipTo, using the alias name ShipTo.
     * @return the value of ShipTo
     */
    public String getShipTo() {
        return (String) getAttributeInternal(SHIPTO);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShipTo.
     * @param value value to set the ShipTo
     */
    public void setShipTo(String value) {
        setAttributeInternal(SHIPTO, value);
    }

    /**
     * Gets the attribute value for RfqDate, using the alias name RfqDate.
     * @return the value of RfqDate
     */
    public Date getRfqDate() {
        return (Date) getAttributeInternal(RFQDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for RfqDate.
     * @param value value to set the RfqDate
     */
    public void setRfqDate(Date value) {
        setAttributeInternal(RFQDATE, value);
    }

    /**
     * Gets the attribute value for DueDate, using the alias name DueDate.
     * @return the value of DueDate
     */
    public Date getDueDate() {
        return (Date) getAttributeInternal(DUEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for DueDate.
     * @param value value to set the DueDate
     */
    public void setDueDate(Date value) {
        setAttributeInternal(DUEDATE, value);
    }

    /**
     * Gets the attribute value for Remarks, using the alias name Remarks.
     * @return the value of Remarks
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Remarks.
     * @param value value to set the Remarks
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for Locationid, using the alias name Locationid.
     * @return the value of Locationid
     */
    public String getLocationid() {
        return (String) getAttributeInternal(LOCATIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Locationid.
     * @param value value to set the Locationid
     */
    public void setLocationid(String value) {
        setAttributeInternal(LOCATIONID, value);
    }

    /**
     * Gets the attribute value for Posted, using the alias name Posted.
     * @return the value of Posted
     */
    public String getPosted() {
        return (String) getAttributeInternal(POSTED);
    }

    /**
     * Sets <code>value</code> as the attribute value for Posted.
     * @param value value to set the Posted
     */
    public void setPosted(String value) {
        setAttributeInternal(POSTED, value);
    }

    /**
     * Gets the attribute value for RfqFor, using the alias name RfqFor.
     * @return the value of RfqFor
     */
    public String getRfqFor() {
        return (String) getAttributeInternal(RFQFOR);
    }

    /**
     * Sets <code>value</code> as the attribute value for RfqFor.
     * @param value value to set the RfqFor
     */
    public void setRfqFor(String value) {
        setAttributeInternal(RFQFOR, value);
    }

    /**
     * Gets the attribute value for FobTermSno, using the alias name FobTermSno.
     * @return the value of FobTermSno
     */
    public Integer getFobTermSno() {
        return (Integer) getAttributeInternal(FOBTERMSNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for FobTermSno.
     * @param value value to set the FobTermSno
     */
    public void setFobTermSno(Integer value) {
        setAttributeInternal(FOBTERMSNO, value);
    }

    /**
     * Gets the attribute value for NoteToSupplier, using the alias name NoteToSupplier.
     * @return the value of NoteToSupplier
     */
    public String getNoteToSupplier() {
        return (String) getAttributeInternal(NOTETOSUPPLIER);
    }

    /**
     * Sets <code>value</code> as the attribute value for NoteToSupplier.
     * @param value value to set the NoteToSupplier
     */
    public void setNoteToSupplier(String value) {
        setAttributeInternal(NOTETOSUPPLIER, value);
    }

    /**
     * Gets the attribute value for ValidFromDate, using the alias name ValidFromDate.
     * @return the value of ValidFromDate
     */
    public Date getValidFromDate() {
        return (Date) getAttributeInternal(VALIDFROMDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ValidFromDate.
     * @param value value to set the ValidFromDate
     */
    public void setValidFromDate(Date value) {
        setAttributeInternal(VALIDFROMDATE, value);
    }

    /**
     * Gets the attribute value for ValidToDate, using the alias name ValidToDate.
     * @return the value of ValidToDate
     */
    public Date getValidToDate() {
        return (Date) getAttributeInternal(VALIDTODATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ValidToDate.
     * @param value value to set the ValidToDate
     */
    public void setValidToDate(Date value) {
        setAttributeInternal(VALIDTODATE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for ModifiedBy, using the alias name ModifiedBy.
     * @return the value of ModifiedBy
     */
    public String getModifiedBy() {
        return (String) getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for ModifiedBy.
     * @param value value to set the ModifiedBy
     */
    public void setModifiedBy(String value) {
        setAttributeInternal(MODIFIEDBY, value);
    }

    /**
     * Gets the attribute value for Modifieddate, using the alias name Modifieddate.
     * @return the value of Modifieddate
     */
    public Date getModifieddate() {
        return (Date) getAttributeInternal(MODIFIEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Modifieddate.
     * @param value value to set the Modifieddate
     */
    public void setModifieddate(Date value) {
        setAttributeInternal(MODIFIEDDATE, value);
    }

    /**
     * Gets the attribute value for Companyid, using the alias name Companyid.
     * @return the value of Companyid
     */
    public String getCompanyid() {
        return (String) getAttributeInternal(COMPANYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Companyid.
     * @param value value to set the Companyid
     */
    public void setCompanyid(String value) {
        setAttributeInternal(COMPANYID, value);
    }

    /**
     * Gets the attribute value for txtLocationName, using the alias name txtLocationName.
     * @return the value of txtLocationName
     */
    public String gettxtLocationName() {
        return (String) getAttributeInternal(TXTLOCATIONNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtLocationName.
     * @param value value to set the txtLocationName
     */
    public void settxtLocationName(String value) {
        setAttributeInternal(TXTLOCATIONNAME, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getSrPurchaseRfqLines() {
        return (RowIterator) getAttributeInternal(SRPURCHASERFQLINES);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getAllLocations() {
        return (EntityImpl) getAttributeInternal(ALLLOCATIONS);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setAllLocations(EntityImpl value) {
        setAttributeInternal(ALLLOCATIONS, value);
    }


    /**
     * @return the associated entity SrPurchaseDemandHeaderImpl.
     */
    public SrPurchaseDemandHeaderImpl getSrPurchaseDemandHeader() {
        return (SrPurchaseDemandHeaderImpl) getAttributeInternal(SRPURCHASEDEMANDHEADER);
    }

    /**
     * Sets <code>value</code> as the associated entity SrPurchaseDemandHeaderImpl.
     */
    public void setSrPurchaseDemandHeader(SrPurchaseDemandHeaderImpl value) {
        setAttributeInternal(SRPURCHASEDEMANDHEADER, value);
    }


    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getSrPurchaseRfqSupplier() {
        return (RowIterator) getAttributeInternal(SRPURCHASERFQSUPPLIER);
    }


    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getSrPurchaseBidHeader() {
        return (RowIterator) getAttributeInternal(SRPURCHASEBIDHEADER);
    }


    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getSrPurchaseBidCompareHeader() {
        return (RowIterator) getAttributeInternal(SRPURCHASEBIDCOMPAREHEADER);
    }


    /**
     * @param rfqheaderseqno key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer rfqheaderseqno) {
        return new Key(new Object[] { rfqheaderseqno });
    }

    @Override
    protected void create(AttributeList attributeList) {
        // TODO Implement this method
        setERPSolPKColumnName("Rfqheaderseqno");
        setERPSolPKSeqName("SR_PURCHASE_RFQ_HEADER_SEQ");
        setLocationid(ERPSolGlobClassModel.doGetUserLocationCode());
    setCompanyid(ERPSolGlobClassModel.doGetUserCompanyCode());
    //        setERPISGenertePK("NO");
    //        SequenceImpl seq = new SequenceImpl("SO_SALES_ORDER_SEQ", getDBTransaction());
    //        setSalesorderseq(seq.getSequenceNumber());
        super.create(attributeList);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        if (operation==DML_INSERT) {
            String pkValue=" sr_purchase_rfq_id('"+ERPSolGlobClassModel.doGetUserCompanyCode()+"','"+ERPSolGlobClassModel.doGetUserLocationCode()+"',TO_DATE('"+getRfqDate()+"','YYYY-MM-DD'))";
            System.out.println(pkValue + "pk value");
            String result= ERPSolGlobClassModel.doGetERPSolPrimaryKeyValueModel(getDBTransaction(), pkValue, "dual", null, null);
            populateAttributeAsChanged(RFQHEADERCODE, result);
        }
        else if (operation==DML_UPDATE) {
            if (getPosted().equals("Y")) {
                populateAttributeAsChanged(MODIFIEDBY, ERPSolGlobClassModel.doGetUserCode());
//               populateAttributeAsChanged(POSTEDDATE, oracle.jbo.domain.Date.getCurrentDate());
               
           }
        }
        super.doDML(operation, e);
    }
}

