package erpsolwom.erpsolwommodel.erpsolwomvo;

import erpsolwom.erpsolwommodel.erpsolwomeo.SrPoReceivingHeaderImpl;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.RowSetIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat May 11 14:16:50 PKT 2024
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SrPoReceivingHeaderVORowImpl extends ViewRowImpl {


    public static final int ENTITY_SRPORECEIVINGHEADER = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Poreceiveseq,
        ReceiveCode,
        Recvdoctypeid,
        Storeid,
        Locationid,
        ReceiveDocumentNo,
        Remarks,
        Companyid,
        CreatedBy,
        CreatedDate,
        ModifiedBy,
        ModifiedDate,
        Posted,
        PostedDate,
        ReceiveDate,
        txtLocationName,
        txtStoreName,
        SrPoReceivingLinesVO,
        AllLocationsVO,
        AllStoresVO,
        SrPurchaseOrderHeaderVO,
        AccAllLocationsVO,
        AccInReceivingDocTypesVO,
        AccSrPurchaseOrderHeaderVO,
        AccAllStoresVO,
        AccSrPurchaseOrderLinesVO;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int PORECEIVESEQ = AttributesEnum.Poreceiveseq.index();
    public static final int RECEIVECODE = AttributesEnum.ReceiveCode.index();
    public static final int RECVDOCTYPEID = AttributesEnum.Recvdoctypeid.index();
    public static final int STOREID = AttributesEnum.Storeid.index();
    public static final int LOCATIONID = AttributesEnum.Locationid.index();
    public static final int RECEIVEDOCUMENTNO = AttributesEnum.ReceiveDocumentNo.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int COMPANYID = AttributesEnum.Companyid.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int MODIFIEDBY = AttributesEnum.ModifiedBy.index();
    public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
    public static final int POSTED = AttributesEnum.Posted.index();
    public static final int POSTEDDATE = AttributesEnum.PostedDate.index();
    public static final int RECEIVEDATE = AttributesEnum.ReceiveDate.index();
    public static final int TXTLOCATIONNAME = AttributesEnum.txtLocationName.index();
    public static final int TXTSTORENAME = AttributesEnum.txtStoreName.index();
    public static final int SRPORECEIVINGLINESVO = AttributesEnum.SrPoReceivingLinesVO.index();
    public static final int ALLLOCATIONSVO = AttributesEnum.AllLocationsVO.index();
    public static final int ALLSTORESVO = AttributesEnum.AllStoresVO.index();
    public static final int SRPURCHASEORDERHEADERVO = AttributesEnum.SrPurchaseOrderHeaderVO.index();
    public static final int ACCALLLOCATIONSVO = AttributesEnum.AccAllLocationsVO.index();
    public static final int ACCINRECEIVINGDOCTYPESVO = AttributesEnum.AccInReceivingDocTypesVO.index();
    public static final int ACCSRPURCHASEORDERHEADERVO = AttributesEnum.AccSrPurchaseOrderHeaderVO.index();
    public static final int ACCALLSTORESVO = AttributesEnum.AccAllStoresVO.index();
    public static final int ACCSRPURCHASEORDERLINESVO = AttributesEnum.AccSrPurchaseOrderLinesVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SrPoReceivingHeaderVORowImpl() {
    }

    /**
     * Gets SrPoReceivingHeader entity object.
     * @return the SrPoReceivingHeader
     */
    public SrPoReceivingHeaderImpl getSrPoReceivingHeader() {
        return (SrPoReceivingHeaderImpl) getEntity(ENTITY_SRPORECEIVINGHEADER);
    }

    /**
     * Gets the attribute value for PORECEIVESEQ using the alias name Poreceiveseq.
     * @return the PORECEIVESEQ
     */
    public Integer getPoreceiveseq() {
        return (Integer) getAttributeInternal(PORECEIVESEQ);
    }

    /**
     * Sets <code>value</code> as attribute value for PORECEIVESEQ using the alias name Poreceiveseq.
     * @param value value to set the PORECEIVESEQ
     */
    public void setPoreceiveseq(Integer value) {
        setAttributeInternal(PORECEIVESEQ, value);
    }

    /**
     * Gets the attribute value for RECEIVE_CODE using the alias name ReceiveCode.
     * @return the RECEIVE_CODE
     */
    public String getReceiveCode() {
        return (String) getAttributeInternal(RECEIVECODE);
    }

    /**
     * Sets <code>value</code> as attribute value for RECEIVE_CODE using the alias name ReceiveCode.
     * @param value value to set the RECEIVE_CODE
     */
    public void setReceiveCode(String value) {
        setAttributeInternal(RECEIVECODE, value);
              
    }

    /**
     * Gets the attribute value for RECVDOCTYPEID using the alias name Recvdoctypeid.
     * @return the RECVDOCTYPEID
     */
    public String getRecvdoctypeid() {
        return (String) getAttributeInternal(RECVDOCTYPEID);
    }

    /**
     * Sets <code>value</code> as attribute value for RECVDOCTYPEID using the alias name Recvdoctypeid.
     * @param value value to set the RECVDOCTYPEID
     */
    public void setRecvdoctypeid(String value) {
        setAttributeInternal(RECVDOCTYPEID, value);
    }

    /**
     * Gets the attribute value for STOREID using the alias name Storeid.
     * @return the STOREID
     */
    public String getStoreid() {
        return (String) getAttributeInternal(STOREID);
    }

    /**
     * Sets <code>value</code> as attribute value for STOREID using the alias name Storeid.
     * @param value value to set the STOREID
     */
    public void setStoreid(String value) {
        setAttributeInternal(STOREID, value);
    }

    /**
     * Gets the attribute value for LOCATIONID using the alias name Locationid.
     * @return the LOCATIONID
     */
    public String getLocationid() {
        return (String) getAttributeInternal(LOCATIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for LOCATIONID using the alias name Locationid.
     * @param value value to set the LOCATIONID
     */
    public void setLocationid(String value) {
        setAttributeInternal(LOCATIONID, value);
    }

    /**
     * Gets the attribute value for RECEIVE_DOCUMENT_NO using the alias name ReceiveDocumentNo.
     * @return the RECEIVE_DOCUMENT_NO
     */
    public String getReceiveDocumentNo() {
        return (String) getAttributeInternal(RECEIVEDOCUMENTNO);
    }

    /**
     * Sets <code>value</code> as attribute value for RECEIVE_DOCUMENT_NO using the alias name ReceiveDocumentNo.
     * @param value value to set the RECEIVE_DOCUMENT_NO
     */
    public void setReceiveDocumentNo(String value) {
        setAttributeInternal(RECEIVEDOCUMENTNO, value);
        while(getSrPoReceivingLinesVO().getRowCount()>0) {
        getSrPoReceivingLinesVO().first().remove();
        }
        
        getAccSrPurchaseOrderLinesVO().setNamedWhereClauseParam("P_ADF_PO_CODE", value==null?"0":value);
        getAccSrPurchaseOrderLinesVO().executeQuery();
        RowSetIterator rsi=getAccSrPurchaseOrderLinesVO();
        while(rsi.hasNext()) {
        Row nextRow =rsi.next();
        Row newRow=getSrPoReceivingLinesVO().createRow();
        newRow.setAttribute("Sourcelinesseq", nextRow.getAttribute("Polinesseq"));
        newRow.setAttribute("ItemId", nextRow.getAttribute("ItemId"));
        newRow.setAttribute("PoRate", nextRow.getAttribute("PoRate"));
        newRow.setAttribute("Quantity", nextRow.getAttribute("Quantity"));
        newRow.setAttribute("DepartmentId", nextRow.getAttribute("DepartmentId"));
        newRow.setAttribute("ProjectId", nextRow.getAttribute("ProjectId"));
        newRow.setAttribute("NetAmount", nextRow.getAttribute("NetAmount"));
        newRow.setAttribute("TaxRate", nextRow.getAttribute("TaxRate"));

        //            newRow.setAttribute("RequesterId", nextRow.getAttribute("RequesterId"));
        getSrPoReceivingLinesVO().insertRow(newRow);
        } 
    }

    /**
     * Gets the attribute value for REMARKS using the alias name Remarks.
     * @return the REMARKS
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as attribute value for REMARKS using the alias name Remarks.
     * @param value value to set the REMARKS
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for COMPANYID using the alias name Companyid.
     * @return the COMPANYID
     */
    public String getCompanyid() {
        return (String) getAttributeInternal(COMPANYID);
    }

    /**
     * Sets <code>value</code> as attribute value for COMPANYID using the alias name Companyid.
     * @param value value to set the COMPANYID
     */
    public void setCompanyid(String value) {
        setAttributeInternal(COMPANYID, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATED_DATE using the alias name CreatedDate.
     * @return the CREATED_DATE
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_DATE using the alias name CreatedDate.
     * @param value value to set the CREATED_DATE
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for MODIFIED_BY using the alias name ModifiedBy.
     * @return the MODIFIED_BY
     */
    public String getModifiedBy() {
        return (String) getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIED_BY using the alias name ModifiedBy.
     * @param value value to set the MODIFIED_BY
     */
    public void setModifiedBy(String value) {
        setAttributeInternal(MODIFIEDBY, value);
    }

    /**
     * Gets the attribute value for MODIFIED_DATE using the alias name ModifiedDate.
     * @return the MODIFIED_DATE
     */
    public Date getModifiedDate() {
        return (Date) getAttributeInternal(MODIFIEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIED_DATE using the alias name ModifiedDate.
     * @param value value to set the MODIFIED_DATE
     */
    public void setModifiedDate(Date value) {
        setAttributeInternal(MODIFIEDDATE, value);
    }

    /**
     * Gets the attribute value for POSTED using the alias name Posted.
     * @return the POSTED
     */
    public String getPosted() {
        return (String) getAttributeInternal(POSTED);
    }

    /**
     * Sets <code>value</code> as attribute value for POSTED using the alias name Posted.
     * @param value value to set the POSTED
     */
    public void setPosted(String value) {
        setAttributeInternal(POSTED, value);
    }

    /**
     * Gets the attribute value for POSTED_DATE using the alias name PostedDate.
     * @return the POSTED_DATE
     */
    public Date getPostedDate() {
        return (Date) getAttributeInternal(POSTEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for POSTED_DATE using the alias name PostedDate.
     * @param value value to set the POSTED_DATE
     */
    public void setPostedDate(Date value) {
        setAttributeInternal(POSTEDDATE, value);
    }

    /**
     * Gets the attribute value for RECEIVE_DATE using the alias name ReceiveDate.
     * @return the RECEIVE_DATE
     */
    public Date getReceiveDate() {
        return (Date) getAttributeInternal(RECEIVEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for RECEIVE_DATE using the alias name ReceiveDate.
     * @param value value to set the RECEIVE_DATE
     */
    public void setReceiveDate(Date value) {
        setAttributeInternal(RECEIVEDATE, value);
    }

    /**
     * Gets the attribute value for TXT_LOCATION_NAME using the alias name txtLocationName.
     * @return the TXT_LOCATION_NAME
     */
    public String gettxtLocationName() {
        return (String) getAttributeInternal(TXTLOCATIONNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_LOCATION_NAME using the alias name txtLocationName.
     * @param value value to set the TXT_LOCATION_NAME
     */
    public void settxtLocationName(String value) {
        setAttributeInternal(TXTLOCATIONNAME, value);
    }

    /**
     * Gets the attribute value for TXT_STORE_NAME using the alias name txtStoreName.
     * @return the TXT_STORE_NAME
     */
    public String gettxtStoreName() {
        return (String) getAttributeInternal(TXTSTORENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_STORE_NAME using the alias name txtStoreName.
     * @param value value to set the TXT_STORE_NAME
     */
    public void settxtStoreName(String value) {
        setAttributeInternal(TXTSTORENAME, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link SrPoReceivingLinesVO.
     */
    public RowIterator getSrPoReceivingLinesVO() {
        return (RowIterator) getAttributeInternal(SRPORECEIVINGLINESVO);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link AllLocationsVO.
     */
    public Row getAllLocationsVO() {
        return (Row) getAttributeInternal(ALLLOCATIONSVO);
    }

    /**
     * Sets the master-detail link AllLocationsVO between this object and <code>value</code>.
     */
    public void setAllLocationsVO(Row value) {
        setAttributeInternal(ALLLOCATIONSVO, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link AllStoresVO.
     */
    public Row getAllStoresVO() {
        return (Row) getAttributeInternal(ALLSTORESVO);
    }

    /**
     * Sets the master-detail link AllStoresVO between this object and <code>value</code>.
     */
    public void setAllStoresVO(Row value) {
        setAttributeInternal(ALLSTORESVO, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link SrPurchaseOrderHeaderVO.
     */
    public Row getSrPurchaseOrderHeaderVO() {
        return (Row) getAttributeInternal(SRPURCHASEORDERHEADERVO);
    }

    /**
     * Sets the master-detail link SrPurchaseOrderHeaderVO between this object and <code>value</code>.
     */
    public void setSrPurchaseOrderHeaderVO(Row value) {
        setAttributeInternal(SRPURCHASEORDERHEADERVO, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccAllLocationsVO.
     */
    public RowSet getAccAllLocationsVO() {
        return (RowSet) getAttributeInternal(ACCALLLOCATIONSVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccInReceivingDocTypesVO.
     */
    public RowSet getAccInReceivingDocTypesVO() {
        return (RowSet) getAttributeInternal(ACCINRECEIVINGDOCTYPESVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccSrPurchaseOrderHeaderVO.
     */
    public RowSet getAccSrPurchaseOrderHeaderVO() {
        return (RowSet) getAttributeInternal(ACCSRPURCHASEORDERHEADERVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccAllStoresVO.
     */
    public RowSet getAccAllStoresVO() {
        return (RowSet) getAttributeInternal(ACCALLSTORESVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccSrPurchaseOrderLinesVO.
     */
    public RowSet getAccSrPurchaseOrderLinesVO() {
        return (RowSet) getAttributeInternal(ACCSRPURCHASEORDERLINESVO);
    }

    @Override
    public boolean isAttributeUpdateable(int i) {
        if (getPosted().equals("Y")) {
            return false;
       }
        return super.isAttributeUpdateable(i);
    }
}

