package erpsolwom.erpsolwommodel.erpsolwomvo;

import erpsolwom.erpsolwommodel.erpsolwomvo.common.SrPurchaseRfqHeaderView;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun May 05 11:05:35 PKT 2024
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SrPurchaseRfqHeaderViewImpl extends ViewObjectImpl implements SrPurchaseRfqHeaderView {
    /**
     * This is the default constructor (do not remove).
     */
    public SrPurchaseRfqHeaderViewImpl() {
    }
    
    public void doSuperviseSrPurchaseRFQ() {
        this.getCurrentRow().setAttribute("Posted", "Y");
        this.getDBTransaction().commit();
    //        CallableStatement cs =
    //            this.getDBTransaction().createCallableStatement("begin ?:=Pkg_Sales_Rebate.FUNC_SUBMIT_SO_REBATE('" +
    //                                                            this.getCurrentRow().getAttribute("RebateId") + "','" +
    //                                                            ERPSolGlobClassModel.doGetUserCode() + "'); END;", 1);
    //        try {
    //            cs.registerOutParameter(1, Types.VARCHAR);
    //            cs.executeUpdate();
    //            this.getCurrentRow().refresh(Row.REFRESH_WITH_DB_FORGET_CHANGES);
    //
    //            if (!cs.getString(1).equals("ERPSOLSUCCESS")) {
    //                this.getDBTransaction().commit();
    //                throw new JboException("Unable to supervise due to " + cs.getString(1));
    //
    //            }
    //            this.getCurrentRow().setAttribute("Posted", "Y");
    //            this.getDBTransaction().commit();
    //        } catch (SQLException e) {
    //            this.getDBTransaction().commit();
    //            System.out.println(e.getMessage() + "this is message");
    //            throw new JboException("Unable to supervise ");
    //        } finally {
    //            try {
    //                cs.close();
    //            } catch (SQLException e) {
    //            }
    //        }
    }

    /**
     * Returns the variable value for P_ADF_SUPPLIERID.
     * @return variable value for P_ADF_SUPPLIERID
     */
    public String getP_ADF_SUPPLIERID() {
        return (String) ensureVariableManager().getVariableValue("P_ADF_SUPPLIERID");
    }

    /**
     * Sets <code>value</code> for variable P_ADF_SUPPLIERID.
     * @param value value to bind as P_ADF_SUPPLIERID
     */
    public void setP_ADF_SUPPLIERID(String value) {
        ensureVariableManager().setVariableValue("P_ADF_SUPPLIERID", value);
    }

    /**
     * Returns the variable value for P_ADF_LOCATIONID.
     * @return variable value for P_ADF_LOCATIONID
     */
    public String getP_ADF_LOCATIONID() {
        return (String) ensureVariableManager().getVariableValue("P_ADF_LOCATIONID");
    }

    /**
     * Sets <code>value</code> for variable P_ADF_LOCATIONID.
     * @param value value to bind as P_ADF_LOCATIONID
     */
    public void setP_ADF_LOCATIONID(String value) {
        ensureVariableManager().setVariableValue("P_ADF_LOCATIONID", value);
    }
}

