package erpsolwom.erpsolwommodel.erpsolwomvo;

import erpsolwom.erpsolwommodel.erpsolwomeo.SrPurchaseBidCompareLinesImpl;

import java.math.BigDecimal;

import oracle.jbo.Row;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri May 10 01:37:35 PKT 2024
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SrPurchaseBidCompareLinesViewRowImpl extends ViewRowImpl {


    public static final int ENTITY_SRPURCHASEBIDCOMPARELINES = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Bidcomparelinesseq,
        Bidcompareheaderseq,
        Bidlinesseq,
        Demandlinesseq,
        Supplierid,
        ItemId,
        BidRate,
        TaxRate,
        NetAmount,
        BidCriteriaSno,
        CreatedBy,
        CreatedDate,
        ModifiedBy,
        Modifieddate,
        IsSelect,
        DepartmentId,
        ProjectId,
        txtItemName,
        Quantity,
        txtSupplierName,
        Rfqlinesseqno,
        PoGenerated,
        GeneratePo,
        SrItemsView,
        SrPurchaseBidCompareHeaderView,
        PuSuppliersVO,
        VwBidCompareForPoGenerateVO,
        AccAllDepartmentsView,
        AccPrgProjectView,
        AccSrBidCriteriaVO;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int BIDCOMPARELINESSEQ = AttributesEnum.Bidcomparelinesseq.index();
    public static final int BIDCOMPAREHEADERSEQ = AttributesEnum.Bidcompareheaderseq.index();
    public static final int BIDLINESSEQ = AttributesEnum.Bidlinesseq.index();
    public static final int DEMANDLINESSEQ = AttributesEnum.Demandlinesseq.index();
    public static final int SUPPLIERID = AttributesEnum.Supplierid.index();
    public static final int ITEMID = AttributesEnum.ItemId.index();
    public static final int BIDRATE = AttributesEnum.BidRate.index();
    public static final int TAXRATE = AttributesEnum.TaxRate.index();
    public static final int NETAMOUNT = AttributesEnum.NetAmount.index();
    public static final int BIDCRITERIASNO = AttributesEnum.BidCriteriaSno.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int MODIFIEDBY = AttributesEnum.ModifiedBy.index();
    public static final int MODIFIEDDATE = AttributesEnum.Modifieddate.index();
    public static final int ISSELECT = AttributesEnum.IsSelect.index();
    public static final int DEPARTMENTID = AttributesEnum.DepartmentId.index();
    public static final int PROJECTID = AttributesEnum.ProjectId.index();
    public static final int TXTITEMNAME = AttributesEnum.txtItemName.index();
    public static final int QUANTITY = AttributesEnum.Quantity.index();
    public static final int TXTSUPPLIERNAME = AttributesEnum.txtSupplierName.index();
    public static final int RFQLINESSEQNO = AttributesEnum.Rfqlinesseqno.index();
    public static final int POGENERATED = AttributesEnum.PoGenerated.index();
    public static final int GENERATEPO = AttributesEnum.GeneratePo.index();
    public static final int SRITEMSVIEW = AttributesEnum.SrItemsView.index();
    public static final int SRPURCHASEBIDCOMPAREHEADERVIEW = AttributesEnum.SrPurchaseBidCompareHeaderView.index();
    public static final int PUSUPPLIERSVO = AttributesEnum.PuSuppliersVO.index();
    public static final int VWBIDCOMPAREFORPOGENERATEVO = AttributesEnum.VwBidCompareForPoGenerateVO.index();
    public static final int ACCALLDEPARTMENTSVIEW = AttributesEnum.AccAllDepartmentsView.index();
    public static final int ACCPRGPROJECTVIEW = AttributesEnum.AccPrgProjectView.index();
    public static final int ACCSRBIDCRITERIAVO = AttributesEnum.AccSrBidCriteriaVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SrPurchaseBidCompareLinesViewRowImpl() {
    }

    /**
     * Gets SrPurchaseBidCompareLines entity object.
     * @return the SrPurchaseBidCompareLines
     */
    public SrPurchaseBidCompareLinesImpl getSrPurchaseBidCompareLines() {
        return (SrPurchaseBidCompareLinesImpl) getEntity(ENTITY_SRPURCHASEBIDCOMPARELINES);
    }

    /**
     * Gets the attribute value for BIDCOMPARELINESSEQ using the alias name Bidcomparelinesseq.
     * @return the BIDCOMPARELINESSEQ
     */
    public Integer getBidcomparelinesseq() {
        return (Integer) getAttributeInternal(BIDCOMPARELINESSEQ);
    }

    /**
     * Sets <code>value</code> as attribute value for BIDCOMPARELINESSEQ using the alias name Bidcomparelinesseq.
     * @param value value to set the BIDCOMPARELINESSEQ
     */
    public void setBidcomparelinesseq(Integer value) {
        setAttributeInternal(BIDCOMPARELINESSEQ, value);
    }

    /**
     * Gets the attribute value for BIDCOMPAREHEADERSEQ using the alias name Bidcompareheaderseq.
     * @return the BIDCOMPAREHEADERSEQ
     */
    public Integer getBidcompareheaderseq() {
        return (Integer) getAttributeInternal(BIDCOMPAREHEADERSEQ);
    }

    /**
     * Sets <code>value</code> as attribute value for BIDCOMPAREHEADERSEQ using the alias name Bidcompareheaderseq.
     * @param value value to set the BIDCOMPAREHEADERSEQ
     */
    public void setBidcompareheaderseq(Integer value) {
        setAttributeInternal(BIDCOMPAREHEADERSEQ, value);
    }

    /**
     * Gets the attribute value for BIDLINESSEQ using the alias name Bidlinesseq.
     * @return the BIDLINESSEQ
     */
    public Integer getBidlinesseq() {
        return (Integer) getAttributeInternal(BIDLINESSEQ);
    }

    /**
     * Sets <code>value</code> as attribute value for BIDLINESSEQ using the alias name Bidlinesseq.
     * @param value value to set the BIDLINESSEQ
     */
    public void setBidlinesseq(Integer value) {
        setAttributeInternal(BIDLINESSEQ, value);
    }

    /**
     * Gets the attribute value for DEMANDLINESSEQ using the alias name Demandlinesseq.
     * @return the DEMANDLINESSEQ
     */
    public Integer getDemandlinesseq() {
        return (Integer) getAttributeInternal(DEMANDLINESSEQ);
    }

    /**
     * Sets <code>value</code> as attribute value for DEMANDLINESSEQ using the alias name Demandlinesseq.
     * @param value value to set the DEMANDLINESSEQ
     */
    public void setDemandlinesseq(Integer value) {
        setAttributeInternal(DEMANDLINESSEQ, value);
    }

    /**
     * Gets the attribute value for SUPPLIERID using the alias name Supplierid.
     * @return the SUPPLIERID
     */
    public String getSupplierid() {
        return (String) getAttributeInternal(SUPPLIERID);
    }

    /**
     * Sets <code>value</code> as attribute value for SUPPLIERID using the alias name Supplierid.
     * @param value value to set the SUPPLIERID
     */
    public void setSupplierid(String value) {
        setAttributeInternal(SUPPLIERID, value);
    }

    /**
     * Gets the attribute value for ITEM_ID using the alias name ItemId.
     * @return the ITEM_ID
     */
    public Integer getItemId() {
        return (Integer) getAttributeInternal(ITEMID);
    }

    /**
     * Sets <code>value</code> as attribute value for ITEM_ID using the alias name ItemId.
     * @param value value to set the ITEM_ID
     */
    public void setItemId(Integer value) {
        setAttributeInternal(ITEMID, value);
    }

    /**
     * Gets the attribute value for BID_RATE using the alias name BidRate.
     * @return the BID_RATE
     */
    public BigDecimal getBidRate() {
        return (BigDecimal) getAttributeInternal(BIDRATE);
    }

    /**
     * Sets <code>value</code> as attribute value for BID_RATE using the alias name BidRate.
     * @param value value to set the BID_RATE
     */
    public void setBidRate(BigDecimal value) {
        setAttributeInternal(BIDRATE, value);
    }

    /**
     * Gets the attribute value for TAX_RATE using the alias name TaxRate.
     * @return the TAX_RATE
     */
    public BigDecimal getTaxRate() {
        return (BigDecimal) getAttributeInternal(TAXRATE);
    }

    /**
     * Sets <code>value</code> as attribute value for TAX_RATE using the alias name TaxRate.
     * @param value value to set the TAX_RATE
     */
    public void setTaxRate(BigDecimal value) {
        setAttributeInternal(TAXRATE, value);
    }

    /**
     * Gets the attribute value for NET_AMOUNT using the alias name NetAmount.
     * @return the NET_AMOUNT
     */
    public BigDecimal getNetAmount() {
        return (BigDecimal) getAttributeInternal(NETAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for NET_AMOUNT using the alias name NetAmount.
     * @param value value to set the NET_AMOUNT
     */
    public void setNetAmount(BigDecimal value) {
        setAttributeInternal(NETAMOUNT, value);
    }

    /**
     * Gets the attribute value for BID_CRITERIA_SNO using the alias name BidCriteriaSno.
     * @return the BID_CRITERIA_SNO
     */
    public Integer getBidCriteriaSno() {
        return (Integer) getAttributeInternal(BIDCRITERIASNO);
    }

    /**
     * Sets <code>value</code> as attribute value for BID_CRITERIA_SNO using the alias name BidCriteriaSno.
     * @param value value to set the BID_CRITERIA_SNO
     */
    public void setBidCriteriaSno(Integer value) {
        setAttributeInternal(BIDCRITERIASNO, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATED_DATE using the alias name CreatedDate.
     * @return the CREATED_DATE
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_DATE using the alias name CreatedDate.
     * @param value value to set the CREATED_DATE
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for MODIFIED_BY using the alias name ModifiedBy.
     * @return the MODIFIED_BY
     */
    public String getModifiedBy() {
        return (String) getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIED_BY using the alias name ModifiedBy.
     * @param value value to set the MODIFIED_BY
     */
    public void setModifiedBy(String value) {
        setAttributeInternal(MODIFIEDBY, value);
    }

    /**
     * Gets the attribute value for MODIFIEDDATE using the alias name Modifieddate.
     * @return the MODIFIEDDATE
     */
    public Date getModifieddate() {
        return (Date) getAttributeInternal(MODIFIEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIEDDATE using the alias name Modifieddate.
     * @param value value to set the MODIFIEDDATE
     */
    public void setModifieddate(Date value) {
        setAttributeInternal(MODIFIEDDATE, value);
    }

    /**
     * Gets the attribute value for IS_SELECT using the alias name IsSelect.
     * @return the IS_SELECT
     */
    public String getIsSelect() {
        return (String) getAttributeInternal(ISSELECT);
    }

    /**
     * Sets <code>value</code> as attribute value for IS_SELECT using the alias name IsSelect.
     * @param value value to set the IS_SELECT
     */
    public void setIsSelect(String value) {
        setAttributeInternal(ISSELECT, value);
    }

    /**
     * Gets the attribute value for DEPARTMENT_ID using the alias name DepartmentId.
     * @return the DEPARTMENT_ID
     */
    public String getDepartmentId() {
        return (String) getAttributeInternal(DEPARTMENTID);
    }

    /**
     * Sets <code>value</code> as attribute value for DEPARTMENT_ID using the alias name DepartmentId.
     * @param value value to set the DEPARTMENT_ID
     */
    public void setDepartmentId(String value) {
        setAttributeInternal(DEPARTMENTID, value);
    }

    /**
     * Gets the attribute value for PROJECT_ID using the alias name ProjectId.
     * @return the PROJECT_ID
     */
    public Integer getProjectId() {
        return (Integer) getAttributeInternal(PROJECTID);
    }

    /**
     * Sets <code>value</code> as attribute value for PROJECT_ID using the alias name ProjectId.
     * @param value value to set the PROJECT_ID
     */
    public void setProjectId(Integer value) {
        setAttributeInternal(PROJECTID, value);
    }

    /**
     * Gets the attribute value for TXT_ITEM_NAME using the alias name txtItemName.
     * @return the TXT_ITEM_NAME
     */
    public String gettxtItemName() {
        return (String) getAttributeInternal(TXTITEMNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_ITEM_NAME using the alias name txtItemName.
     * @param value value to set the TXT_ITEM_NAME
     */
    public void settxtItemName(String value) {
        setAttributeInternal(TXTITEMNAME, value);
    }

    /**
     * Gets the attribute value for QUANTITY using the alias name Quantity.
     * @return the QUANTITY
     */
    public BigDecimal getQuantity() {
        return (BigDecimal) getAttributeInternal(QUANTITY);
    }

    /**
     * Sets <code>value</code> as attribute value for QUANTITY using the alias name Quantity.
     * @param value value to set the QUANTITY
     */
    public void setQuantity(BigDecimal value) {
        setAttributeInternal(QUANTITY, value);
    }

    /**
     * Gets the attribute value for TXT_SUPPLIER_NAME using the alias name txtSupplierName.
     * @return the TXT_SUPPLIER_NAME
     */
    public String gettxtSupplierName() {
        return (String) getAttributeInternal(TXTSUPPLIERNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_SUPPLIER_NAME using the alias name txtSupplierName.
     * @param value value to set the TXT_SUPPLIER_NAME
     */
    public void settxtSupplierName(String value) {
        setAttributeInternal(TXTSUPPLIERNAME, value);
    }

    /**
     * Gets the attribute value for RFQLINESSEQNO using the alias name Rfqlinesseqno.
     * @return the RFQLINESSEQNO
     */
    public Long getRfqlinesseqno() {
        return (Long) getAttributeInternal(RFQLINESSEQNO);
    }

    /**
     * Sets <code>value</code> as attribute value for RFQLINESSEQNO using the alias name Rfqlinesseqno.
     * @param value value to set the RFQLINESSEQNO
     */
    public void setRfqlinesseqno(Long value) {
        setAttributeInternal(RFQLINESSEQNO, value);
    }

    /**
     * Gets the attribute value for PO_GENERATED using the alias name PoGenerated.
     * @return the PO_GENERATED
     */
    public String getPoGenerated() {
        return (String) getAttributeInternal(POGENERATED);
    }

    /**
     * Sets <code>value</code> as attribute value for PO_GENERATED using the alias name PoGenerated.
     * @param value value to set the PO_GENERATED
     */
    public void setPoGenerated(String value) {
        setAttributeInternal(POGENERATED, value);
    }

    /**
     * Gets the attribute value for GENERATE_PO using the alias name GeneratePo.
     * @return the GENERATE_PO
     */
    public String getGeneratePo() {
        return (String) getAttributeInternal(GENERATEPO);
    }

    /**
     * Sets <code>value</code> as attribute value for GENERATE_PO using the alias name GeneratePo.
     * @param value value to set the GENERATE_PO
     */
    public void setGeneratePo(String value) {
        setAttributeInternal(GENERATEPO, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link SrItemsView.
     */
    public Row getSrItemsView() {
        return (Row) getAttributeInternal(SRITEMSVIEW);
    }

    /**
     * Sets the master-detail link SrItemsView between this object and <code>value</code>.
     */
    public void setSrItemsView(Row value) {
        setAttributeInternal(SRITEMSVIEW, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link SrPurchaseBidCompareHeaderView.
     */
    public Row getSrPurchaseBidCompareHeaderView() {
        return (Row) getAttributeInternal(SRPURCHASEBIDCOMPAREHEADERVIEW);
    }

    /**
     * Sets the master-detail link SrPurchaseBidCompareHeaderView between this object and <code>value</code>.
     */
    public void setSrPurchaseBidCompareHeaderView(Row value) {
        setAttributeInternal(SRPURCHASEBIDCOMPAREHEADERVIEW, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link PuSuppliersVO.
     */
    public Row getPuSuppliersVO() {
        return (Row) getAttributeInternal(PUSUPPLIERSVO);
    }

    /**
     * Sets the master-detail link PuSuppliersVO between this object and <code>value</code>.
     */
    public void setPuSuppliersVO(Row value) {
        setAttributeInternal(PUSUPPLIERSVO, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link VwBidCompareForPoGenerateVO.
     */
    public Row getVwBidCompareForPoGenerateVO() {
        return (Row) getAttributeInternal(VWBIDCOMPAREFORPOGENERATEVO);
    }

    /**
     * Sets the master-detail link VwBidCompareForPoGenerateVO between this object and <code>value</code>.
     */
    public void setVwBidCompareForPoGenerateVO(Row value) {
        setAttributeInternal(VWBIDCOMPAREFORPOGENERATEVO, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccAllDepartmentsView.
     */
    public RowSet getAccAllDepartmentsView() {
        return (RowSet) getAttributeInternal(ACCALLDEPARTMENTSVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccPrgProjectView.
     */
    public RowSet getAccPrgProjectView() {
        return (RowSet) getAttributeInternal(ACCPRGPROJECTVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccSrBidCriteriaVO.
     */
    public RowSet getAccSrBidCriteriaVO() {
        return (RowSet) getAttributeInternal(ACCSRBIDCRITERIAVO);
    }
    @Override
    public boolean isAttributeUpdateable(int i) {
        if (getSrPurchaseBidCompareHeaderView().getAttribute("Posted").equals("Y")) {
            return false;
       }
        return super.isAttributeUpdateable(i);
    }
}

