package erpsolwom.erpsolwommodel.erpsolwomvo;

import erpsolwom.erpsolwommodel.erpsolwomeo.SrPurchaseBidHeaderImpl;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.RowSetIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed May 08 00:10:58 PKT 2024
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SrPurchaseBidHeaderViewRowImpl extends ViewRowImpl {


    public static final int ENTITY_SRPURCHASEBIDHEADER = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Bidheaderseq,
        BidCode,
        BidDate,
        DemandCode,
        SupplierQuoteNo,
        RfqHeaderCode,
        Supplierid,
        Remarks,
        Locationid,
        ResponseDate,
        Posted,
        EffectiveFrom,
        EffectiveTo,
        Companyid,
        CreatedBy,
        CreatedDate,
        ModifiedBy,
        Modifieddate,
        txtLocationName,
        Rfqsupplierseqno,
        txtSupplierName,
        SrPurchaseBidLinesView,
        AllLocationsVO,
        SrPurchaseRfqSupplierView,
        PuSuppliersVO,
        SrPurchaseRfqHeaderView,
        AccAllLocationsVO,
        AccPuSuppliersVO,
        AccSrPurchaseRfqHeaderView,
        AccSrPurchaseRfqSupplierView,
        AccSrPurchaseRfqLinesView;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int BIDHEADERSEQ = AttributesEnum.Bidheaderseq.index();
    public static final int BIDCODE = AttributesEnum.BidCode.index();
    public static final int BIDDATE = AttributesEnum.BidDate.index();
    public static final int DEMANDCODE = AttributesEnum.DemandCode.index();
    public static final int SUPPLIERQUOTENO = AttributesEnum.SupplierQuoteNo.index();
    public static final int RFQHEADERCODE = AttributesEnum.RfqHeaderCode.index();
    public static final int SUPPLIERID = AttributesEnum.Supplierid.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int LOCATIONID = AttributesEnum.Locationid.index();
    public static final int RESPONSEDATE = AttributesEnum.ResponseDate.index();
    public static final int POSTED = AttributesEnum.Posted.index();
    public static final int EFFECTIVEFROM = AttributesEnum.EffectiveFrom.index();
    public static final int EFFECTIVETO = AttributesEnum.EffectiveTo.index();
    public static final int COMPANYID = AttributesEnum.Companyid.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int MODIFIEDBY = AttributesEnum.ModifiedBy.index();
    public static final int MODIFIEDDATE = AttributesEnum.Modifieddate.index();
    public static final int TXTLOCATIONNAME = AttributesEnum.txtLocationName.index();
    public static final int RFQSUPPLIERSEQNO = AttributesEnum.Rfqsupplierseqno.index();
    public static final int TXTSUPPLIERNAME = AttributesEnum.txtSupplierName.index();
    public static final int SRPURCHASEBIDLINESVIEW = AttributesEnum.SrPurchaseBidLinesView.index();
    public static final int ALLLOCATIONSVO = AttributesEnum.AllLocationsVO.index();
    public static final int SRPURCHASERFQSUPPLIERVIEW = AttributesEnum.SrPurchaseRfqSupplierView.index();
    public static final int PUSUPPLIERSVO = AttributesEnum.PuSuppliersVO.index();
    public static final int SRPURCHASERFQHEADERVIEW = AttributesEnum.SrPurchaseRfqHeaderView.index();
    public static final int ACCALLLOCATIONSVO = AttributesEnum.AccAllLocationsVO.index();
    public static final int ACCPUSUPPLIERSVO = AttributesEnum.AccPuSuppliersVO.index();
    public static final int ACCSRPURCHASERFQHEADERVIEW = AttributesEnum.AccSrPurchaseRfqHeaderView.index();
    public static final int ACCSRPURCHASERFQSUPPLIERVIEW = AttributesEnum.AccSrPurchaseRfqSupplierView.index();
    public static final int ACCSRPURCHASERFQLINESVIEW = AttributesEnum.AccSrPurchaseRfqLinesView.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SrPurchaseBidHeaderViewRowImpl() {
    }

    /**
     * Gets SrPurchaseBidHeader entity object.
     * @return the SrPurchaseBidHeader
     */
    public SrPurchaseBidHeaderImpl getSrPurchaseBidHeader() {
        return (SrPurchaseBidHeaderImpl) getEntity(ENTITY_SRPURCHASEBIDHEADER);
    }

    /**
     * Gets the attribute value for BIDHEADERSEQ using the alias name Bidheaderseq.
     * @return the BIDHEADERSEQ
     */
    public Integer getBidheaderseq() {
        return (Integer) getAttributeInternal(BIDHEADERSEQ);
    }

    /**
     * Sets <code>value</code> as attribute value for BIDHEADERSEQ using the alias name Bidheaderseq.
     * @param value value to set the BIDHEADERSEQ
     */
    public void setBidheaderseq(Integer value) {
        setAttributeInternal(BIDHEADERSEQ, value);
    }

    /**
     * Gets the attribute value for BID_CODE using the alias name BidCode.
     * @return the BID_CODE
     */
    public String getBidCode() {
        return (String) getAttributeInternal(BIDCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for BID_CODE using the alias name BidCode.
     * @param value value to set the BID_CODE
     */
    public void setBidCode(String value) {
        setAttributeInternal(BIDCODE, value);
    }

    /**
     * Gets the attribute value for BID_DATE using the alias name BidDate.
     * @return the BID_DATE
     */
    public Date getBidDate() {
        return (Date) getAttributeInternal(BIDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for BID_DATE using the alias name BidDate.
     * @param value value to set the BID_DATE
     */
    public void setBidDate(Date value) {
        setAttributeInternal(BIDDATE, value);
    }

    /**
     * Gets the attribute value for DEMAND_CODE using the alias name DemandCode.
     * @return the DEMAND_CODE
     */
    public String getDemandCode() {
        return (String) getAttributeInternal(DEMANDCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for DEMAND_CODE using the alias name DemandCode.
     * @param value value to set the DEMAND_CODE
     */
    public void setDemandCode(String value) {
        setAttributeInternal(DEMANDCODE, value);
    }

    /**
     * Gets the attribute value for SUPPLIER_QUOTE_NO using the alias name SupplierQuoteNo.
     * @return the SUPPLIER_QUOTE_NO
     */
    public String getSupplierQuoteNo() {
        return (String) getAttributeInternal(SUPPLIERQUOTENO);
    }

    /**
     * Sets <code>value</code> as attribute value for SUPPLIER_QUOTE_NO using the alias name SupplierQuoteNo.
     * @param value value to set the SUPPLIER_QUOTE_NO
     */
    public void setSupplierQuoteNo(String value) {
        setAttributeInternal(SUPPLIERQUOTENO, value);
    }

    /**
     * Gets the attribute value for RFQ_HEADER_CODE using the alias name RfqHeaderCode.
     * @return the RFQ_HEADER_CODE
     */
    public String getRfqHeaderCode() {
        return (String) getAttributeInternal(RFQHEADERCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for RFQ_HEADER_CODE using the alias name RfqHeaderCode.
     * @param value value to set the RFQ_HEADER_CODE
     */
    public void setRfqHeaderCode(String value) {
        setAttributeInternal(RFQHEADERCODE, value);
                getAccSrPurchaseRfqSupplierView().setNamedWhereClauseParam("P_ADF_RFQ_HEADER_CODE", value==null?-1:value);
                getAccSrPurchaseRfqSupplierView().setNamedWhereClauseParam("P_ADF_SUPPLIERID", getSupplierid()==null?-1:getSupplierid());
                getAccSrPurchaseRfqSupplierView().executeQuery();
                setRfqsupplierseqno((Integer)getAccSrPurchaseRfqSupplierView().first().getAttribute("Rfqsupplierseqno"));
 
        while(getSrPurchaseBidLinesView().getRowCount()>0) {
            getSrPurchaseBidLinesView().first().remove();
        }
        
        getAccSrPurchaseRfqLinesView().setNamedWhereClauseParam("P_ADF_RFQ_HEADER_CODE", value==null?"0":value);
        getAccSrPurchaseRfqLinesView().executeQuery();
        RowSetIterator rsi=getAccSrPurchaseRfqLinesView();
        while(rsi.hasNext()) {
            Row nextRow =rsi.next();
            Row newRow=getSrPurchaseBidLinesView().createRow();
            newRow.setAttribute("Demandlinesseq", nextRow.getAttribute("Demandlinesseq"));
            newRow.setAttribute("Rfqlinesseqno", nextRow.getAttribute("Rfqlinesseqno"));

            newRow.setAttribute("ItemId", nextRow.getAttribute("ItemId"));
            newRow.setAttribute("BidPrice", nextRow.getAttribute("AproxPrice"));
            newRow.setAttribute("Quantity", nextRow.getAttribute("Quantity"));
            newRow.setAttribute("DepartmentId", nextRow.getAttribute("DepartmentId"));
            newRow.setAttribute("ProjectId", nextRow.getAttribute("ProjectId"));
        //            newRow.setAttribute("RequesterId", nextRow.getAttribute("RequesterId"));
            getSrPurchaseBidLinesView().insertRow(newRow);
        }       
    }

    /**
     * Gets the attribute value for SUPPLIERID using the alias name Supplierid.
     * @return the SUPPLIERID
     */
    public String getSupplierid() {
        return (String) getAttributeInternal(SUPPLIERID);
    }

    /**
     * Sets <code>value</code> as attribute value for SUPPLIERID using the alias name Supplierid.
     * @param value value to set the SUPPLIERID
     */
    public void setSupplierid(String value) {
        setAttributeInternal(SUPPLIERID, value);
//        setAttributeInternal(SUPPLIERID, value);
//        getAccSrPurchaseRfqSupplierView().setNamedWhereClauseParam("P_ADF_SUPPLIERID", value==null?-1:value);
//        getAccSrPurchaseRfqSupplierView().setNamedWhereClauseParam("P_ADF_RFQ_HEADER_CODE", getRfqHeaderCode()==null?-1:getRfqHeaderCode());
//        getAccSrPurchaseRfqSupplierView().executeQuery();
//        setRfqsupplierseqno((Integer)getAccSrPurchaseRfqSupplierView().first().getAttribute("Rfqsupplierseqno"));
    }

    /**
     * Gets the attribute value for REMARKS using the alias name Remarks.
     * @return the REMARKS
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as attribute value for REMARKS using the alias name Remarks.
     * @param value value to set the REMARKS
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for LOCATIONID using the alias name Locationid.
     * @return the LOCATIONID
     */
    public String getLocationid() {
        return (String) getAttributeInternal(LOCATIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for LOCATIONID using the alias name Locationid.
     * @param value value to set the LOCATIONID
     */
    public void setLocationid(String value) {
        setAttributeInternal(LOCATIONID, value);
    }

    /**
     * Gets the attribute value for RESPONSE_DATE using the alias name ResponseDate.
     * @return the RESPONSE_DATE
     */
    public Date getResponseDate() {
        return (Date) getAttributeInternal(RESPONSEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for RESPONSE_DATE using the alias name ResponseDate.
     * @param value value to set the RESPONSE_DATE
     */
    public void setResponseDate(Date value) {
        setAttributeInternal(RESPONSEDATE, value);
    }

    /**
     * Gets the attribute value for POSTED using the alias name Posted.
     * @return the POSTED
     */
    public String getPosted() {
        return (String) getAttributeInternal(POSTED);
    }

    /**
     * Sets <code>value</code> as attribute value for POSTED using the alias name Posted.
     * @param value value to set the POSTED
     */
    public void setPosted(String value) {
        setAttributeInternal(POSTED, value);
    }

    /**
     * Gets the attribute value for EFFECTIVE_FROM using the alias name EffectiveFrom.
     * @return the EFFECTIVE_FROM
     */
    public Date getEffectiveFrom() {
        return (Date) getAttributeInternal(EFFECTIVEFROM);
    }

    /**
     * Sets <code>value</code> as attribute value for EFFECTIVE_FROM using the alias name EffectiveFrom.
     * @param value value to set the EFFECTIVE_FROM
     */
    public void setEffectiveFrom(Date value) {
        setAttributeInternal(EFFECTIVEFROM, value);
    }

    /**
     * Gets the attribute value for EFFECTIVE_TO using the alias name EffectiveTo.
     * @return the EFFECTIVE_TO
     */
    public Date getEffectiveTo() {
        return (Date) getAttributeInternal(EFFECTIVETO);
    }

    /**
     * Sets <code>value</code> as attribute value for EFFECTIVE_TO using the alias name EffectiveTo.
     * @param value value to set the EFFECTIVE_TO
     */
    public void setEffectiveTo(Date value) {
        setAttributeInternal(EFFECTIVETO, value);
    }

    /**
     * Gets the attribute value for COMPANYID using the alias name Companyid.
     * @return the COMPANYID
     */
    public String getCompanyid() {
        return (String) getAttributeInternal(COMPANYID);
    }

    /**
     * Sets <code>value</code> as attribute value for COMPANYID using the alias name Companyid.
     * @param value value to set the COMPANYID
     */
    public void setCompanyid(String value) {
        setAttributeInternal(COMPANYID, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATED_DATE using the alias name CreatedDate.
     * @return the CREATED_DATE
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_DATE using the alias name CreatedDate.
     * @param value value to set the CREATED_DATE
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for MODIFIED_BY using the alias name ModifiedBy.
     * @return the MODIFIED_BY
     */
    public String getModifiedBy() {
        return (String) getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIED_BY using the alias name ModifiedBy.
     * @param value value to set the MODIFIED_BY
     */
    public void setModifiedBy(String value) {
        setAttributeInternal(MODIFIEDBY, value);
    }

    /**
     * Gets the attribute value for MODIFIEDDATE using the alias name Modifieddate.
     * @return the MODIFIEDDATE
     */
    public Date getModifieddate() {
        return (Date) getAttributeInternal(MODIFIEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIEDDATE using the alias name Modifieddate.
     * @param value value to set the MODIFIEDDATE
     */
    public void setModifieddate(Date value) {
        setAttributeInternal(MODIFIEDDATE, value);
    }

    /**
     * Gets the attribute value for TXT_LOCATION_NAME using the alias name txtLocationName.
     * @return the TXT_LOCATION_NAME
     */
    public String gettxtLocationName() {
        return (String) getAttributeInternal(TXTLOCATIONNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_LOCATION_NAME using the alias name txtLocationName.
     * @param value value to set the TXT_LOCATION_NAME
     */
    public void settxtLocationName(String value) {
        setAttributeInternal(TXTLOCATIONNAME, value);
    }

    /**
     * Gets the attribute value for RFQSUPPLIERSEQNO using the alias name Rfqsupplierseqno.
     * @return the RFQSUPPLIERSEQNO
     */
    public Integer getRfqsupplierseqno() {
        return (Integer) getAttributeInternal(RFQSUPPLIERSEQNO);
    }

    /**
     * Sets <code>value</code> as attribute value for RFQSUPPLIERSEQNO using the alias name Rfqsupplierseqno.
     * @param value value to set the RFQSUPPLIERSEQNO
     */
    public void setRfqsupplierseqno(Integer value) {
        setAttributeInternal(RFQSUPPLIERSEQNO, value);
    }

    /**
     * Gets the attribute value for TXT_SUPPLIER_NAME using the alias name txtSupplierName.
     * @return the TXT_SUPPLIER_NAME
     */
    public String gettxtSupplierName() {
        return (String) getAttributeInternal(TXTSUPPLIERNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_SUPPLIER_NAME using the alias name txtSupplierName.
     * @param value value to set the TXT_SUPPLIER_NAME
     */
    public void settxtSupplierName(String value) {
        setAttributeInternal(TXTSUPPLIERNAME, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link SrPurchaseBidLinesView.
     */
    public RowIterator getSrPurchaseBidLinesView() {
        return (RowIterator) getAttributeInternal(SRPURCHASEBIDLINESVIEW);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link AllLocationsVO.
     */
    public Row getAllLocationsVO() {
        return (Row) getAttributeInternal(ALLLOCATIONSVO);
    }

    /**
     * Sets the master-detail link AllLocationsVO between this object and <code>value</code>.
     */
    public void setAllLocationsVO(Row value) {
        setAttributeInternal(ALLLOCATIONSVO, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link SrPurchaseRfqSupplierView.
     */
    public Row getSrPurchaseRfqSupplierView() {
        return (Row) getAttributeInternal(SRPURCHASERFQSUPPLIERVIEW);
    }

    /**
     * Sets the master-detail link SrPurchaseRfqSupplierView between this object and <code>value</code>.
     */
    public void setSrPurchaseRfqSupplierView(Row value) {
        setAttributeInternal(SRPURCHASERFQSUPPLIERVIEW, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link PuSuppliersVO.
     */
    public Row getPuSuppliersVO() {
        return (Row) getAttributeInternal(PUSUPPLIERSVO);
    }

    /**
     * Sets the master-detail link PuSuppliersVO between this object and <code>value</code>.
     */
    public void setPuSuppliersVO(Row value) {
        setAttributeInternal(PUSUPPLIERSVO, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link SrPurchaseRfqHeaderView.
     */
    public Row getSrPurchaseRfqHeaderView() {
        return (Row) getAttributeInternal(SRPURCHASERFQHEADERVIEW);
    }

    /**
     * Sets the master-detail link SrPurchaseRfqHeaderView between this object and <code>value</code>.
     */
    public void setSrPurchaseRfqHeaderView(Row value) {
        setAttributeInternal(SRPURCHASERFQHEADERVIEW, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccAllLocationsVO.
     */
    public RowSet getAccAllLocationsVO() {
        return (RowSet) getAttributeInternal(ACCALLLOCATIONSVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccPuSuppliersVO.
     */
    public RowSet getAccPuSuppliersVO() {
        return (RowSet) getAttributeInternal(ACCPUSUPPLIERSVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccSrPurchaseRfqHeaderView.
     */
    public RowSet getAccSrPurchaseRfqHeaderView() {
        return (RowSet) getAttributeInternal(ACCSRPURCHASERFQHEADERVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccSrPurchaseRfqSupplierView.
     */
    public RowSet getAccSrPurchaseRfqSupplierView() {
        return (RowSet) getAttributeInternal(ACCSRPURCHASERFQSUPPLIERVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccSrPurchaseRfqLinesView.
     */
    public RowSet getAccSrPurchaseRfqLinesView() {
        return (RowSet) getAttributeInternal(ACCSRPURCHASERFQLINESVIEW);
    }
    
    @Override
    public boolean isAttributeUpdateable(int i) {
        if (getPosted().equals("Y")) {
            return false;
       }
        return super.isAttributeUpdateable(i);
    }
}

