package erpsolwom.erpsolwommodel.erpsolwomvo;

import erpsolwom.erpsolwommodel.erpsolwomvo.common.SrPurchaseBidCompareHeaderView;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed May 08 23:22:43 PKT 2024
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SrPurchaseBidCompareHeaderViewImpl extends ViewObjectImpl implements SrPurchaseBidCompareHeaderView {
    /**
     * This is the default constructor (do not remove).
     */
    public SrPurchaseBidCompareHeaderViewImpl() {
    }
    public void doSuperviseSrPurchaseComp() {
        this.getCurrentRow().setAttribute("Posted", "Y");
        this.getDBTransaction().commit();
        
    }
}

